spring:
  profiles:
    group:
      local:
        - app-local
        - aws
        - db-local
        - mail
      dev:
        - app-dev
        - aws
        - db-dev
        - mail
    active: local
